### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by dyygtfx** [windy/wblog#30]
刚接触 rails ，打算弄个博客开始折腾，今天用你这个程序在国内 coding.net 上面部署，出现问题了 We're sorry, but something went wrong.
它这个是一键部署的，不知道怎么配置数据库这些东西，不知道有没有时间看下怎么部署

**Comment by windy** [comment]
建议先在本地安装对应的环境跑起来先熟悉之后, 再着手布署到云端, 其间, 可以多看看看 rails 相关的资料.

coding.net 目前对新手很不友好, 等他们有文档了建议再折腾它.  如果后面有时间, 我先尝试布署一个上去, 再做个文档. 你再 follow 即可.

**Comment by dyygtfx** [comment]
谢谢，之前是看那本电子书在 heroku 上直接 push 上去，但是自己还没具体实践过 Rails 和数据库有关的操作，我再去熟悉熟悉
