### ISSUE TITLE
Some suggest for wblog

### ISSUE THREAD

**Issue by suujonH** [windy/wblog#31]
1.首页只有一篇文章觉得怪怪的。
    当我 第一次踏入这个blog时，看完了最新的文章想看其他文章，于是我点了很多次logo却还是只有一篇，错误的以为只有一篇文章。不过我也不知道怎么改比较好XD

2.建议顶部工具栏固定置顶或者鼠标放上后悬浮出。否则每次看完文章以后想切换栏目还要手动返回顶部打开抽屉切换。

3.搜索功能

**Comment by windy** [comment]
收到. 可能会考虑做一些优化. 但不是特别好处理.
