### ISSUE TITLE
Could not find activesupport-4.1.9

### ISSUE THREAD

**Issue by caiqinghua** [windy/wblog#37]
wblog caiqinghua$ bundle install
Fetching source index from http://ruby.taobao.org/
Could not find activesupport-4.1.9 in any of the sources

**Comment by caiqinghua** [comment]
qinghuadeMacBook-Pro:wblog caiqinghua$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies....
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/thread_safe-0.3.4.gem)
An error occurred while installing thread_safe (0.3.4), and Bundler cannot continue.
Make sure that `gem install thread_safe -v '0.3.4'` succeeds before bundling.
qinghuadeMacBook-Pro:wblog caiqinghua$ gem install thread_safe -v '0.3.4'
Fetching: thread_safe-0.3.4.gem (100%)
Successfully installed thread_safe-0.3.4
Parsing documentation for thread_safe-0.3.4
Installing ri documentation for thread_safe-0.3.4
Done installing documentation for thread_safe after 0 seconds
1 gem installed

**Comment by windy** [comment]
用 rubygems.org 的话必须翻墙.

用 ruby.taobao.org 应该没问题, 可以重试一下.

**Comment by caiqinghua** [comment]
Could not find activesupport-4.1.9 in any of the sources when using ruby.taobao.org

**Comment by windy** [comment]
@caiqinghua Just try to change to  https://ruby.taobao.org and try `bundle install` again.
