### ISSUE TITLE
cp: config/database.yml.example: No such file or directory

### ISSUE THREAD

**Issue by caiqinghua** [windy/wblog#38]
cp config/database.yml.example config/database.yml
cp: config/database.yml.example: No such file or directory

**Comment by windy** [comment]
这里有误


应该是


cp config/mongoid.yml.example config/mongoid.yml


还要安装一下 mongodb.




Original Message
Sender:Linnotifications@github.com
Recipient:windy/wblogwblog@noreply.github.com
Date:Monday, Apr 27, 2015 22:05
Subject:[wblog] cp: config/database.yml.example: No such file or directory(#38)


cp config/database.yml.example config/database.yml
 cp: config/database.yml.example: No such file or directory
