### ISSUE TITLE
Suggestion for comment reviewing system

### ISSUE THREAD

**Issue by budhrg** [windy/wblog#39]
Hi Windy,

First of all I would like to thank for such nice and open source blogging system and that too in my favorite language 'Ruby'.
I was really looking for this one.
I setup `wblog` locally and created few demo blogs etc.

I like the UI/UX of a blog post and commenting feature.
However, whenever user comment on the blog post, it directly display the comments at the bottom of the blog.

Wouldn't it be good to display those comments after blog owner review?

I am a RoR full stack developer like you :smile: and would like to contribute in making `wblog` as ideal blogging platform.

Thanks

**Comment by windy** [comment]
Hi bughrg,

I'm glad to hear your message for `wblog`.

`wblog`'s front end is built with angularjs which is a popular front end framework right now. If you want add a approved comment feature, you should learn and write your code for it.

I think it's suitable for someone but not to all.

If you like, you can try to complete this feature and give me a pull request, remember, this feature should be configurable.

Regards,
Windy

**Comment by budhrg** [comment]
Sure Windy.
Thanks
