### ISSUE TITLE
已删除的post再次访问会进入rails的报错界面

### ISSUE THREAD

**Issue by sxysxy** [windy/wblog#48]
例如第一篇文章已经删除了，地址栏输入进入/blogs/1，会进入rails报错界面(ActiveRecord::RecordNotFound)，希望能优美地处理这个。（进入到一个比较漂亮的报错界面什么的）

**Comment by windy** [comment]
@sxysxy 可以自行修改 `public/404.html` 来调整样式.

**Comment by sxysxy** [comment]
@windy 好的。我直接添加了新的action处理了这些问题。这是我用您的博客系统做的博客的地址 http://115.28.164.3 。非常感谢您提供这么棒的博客系统！

**Comment by windy** [comment]
@sxysxy Nice 👍 , 关注中 :)
