### ISSUE TITLE
以production环境运用网站无法正常显示ui

### ISSUE THREAD

**Issue by sxysxy** [windy/wblog#50]
development模式一切正常，production模式打开网页几乎变成了纯文本，美丽的ui全没了......
http:\\sxysxy.org 最近发现运行吃内存太严重，想以production方式运行然后就RT.

**Comment by windy** [comment]
你怎么布署的?

**Comment by windy** [comment]
看一下这里:  https://github.com/windy/wblog/wiki

**Comment by sxysxy** [comment]
嗯，我没有使用rvm，我的nginx也并没有那样配置(我只是简单的转发80的数据到3000)

**Comment by windy** [comment]
建议你用 nginx + wblog 的方式布署. 才能保证可靠依内存运行.

**Comment by sxysxy** [comment]
嗯。。。那这个production模式下网站不能正常显示是怎么了?我搜了一圈大概是assets预编译的问题?Orz

**Comment by windy** [comment]
production 模式下,  js 和 css 会打包起来, 放在 public 里面. 默认 rails app 不管 public, 要交给 nginx 托管. 所以如果配置不对, 就加载不了 js 和 css 了.

**Comment by sxysxy** [comment]
原来如此。🙏3kyu
