### ISSUE TITLE
拒绝连接，但我的端口并未被占用

### ISSUE THREAD

**Issue by KeyLD** [windy/wblog#51]
你好，我是一个rails初学者，非常喜欢您的博客，并想通过您的博客学习rails。
但是我在按照readme照做之后并启动之后出现了这样的错误
>     Puma caught this error: could not connect to server: Connection refused
>	Is the server running on host "localhost" (::1) and accepting
>	TCP/IP connections on port 5432?
>      could not connect to server: Connection refused
>	Is the server running on host "localhost" (127.0.0.1) and accepting
>	TCP/IP connections on port 5432?
>     (PG::ConnectionBad)
>      ...(后面一大堆)

我通过 `sudo netstat -an | grep 5432` 发现并没有任何输出

请问这是什么原因？我应该如何做？

**Comment by windy** [comment]
5432 是 postgresql 数据库的端口, 说明你没有正确启动它. 研究一下解决一下.

**Comment by KeyLD** [comment]
非常抱歉，我应该先去学postgresql的。
十分感谢，问题已解决。
