### ISSUE TITLE
配置管理员账户出现问题？

### ISSUE THREAD

**Issue by babyhai** [windy/wblog#53]
我再调试一个问题的时候没有弄好，就重新从git上拉代码到服务器上 所以的 除了管理员账户没有配置 其他的都配置了 也可以运行 。这是配置文件
config/application.yml
`

1
--
# This section MUST be configured
  | SITE_NAME: "Haley's Blog"
  | # Admin Dashboard Management, If ADMIN_USER is blank, No One can login into Dashboard
  | # Recommend using your personal Email, if SENDCLOUD_USER is setted, System WILL send you notification email.
  | # For more detail, see: /app/models/comment.rb
  | ADMIN_USER: 'mandy'
  | ADMIN_PASSWORD: '*******'
  |  
  |  
  | # Rails secret token, use `rake secret` to generate new one here.
  | SECRET_TOKEN: 'e4122773d4324fce978c52cde790d84d14f7194f377aea41b7b8302d1d10150e6076a3b7e5e0c1f24ca330cf0a058482c95e
  |  
  | #locale: en or zh-CN, zh-CN is default value
  | LOCALE: 'zh-CN'
  |  
  | # sidekiq redis namespace, if you configure two blog in on VPS, you should change it.
  | # default is wblog
  | REDIS_NAMESPACE: 'wblog'
  |  
  | # META description for SEO
  | INTRODUCE: '一个缺口的被子，换个角度看它，它仍然是圆的'
  |  
  | #Website Address for footer display without http
  | # SITE_ADDRESS: 'yafeilee.me'
  | #SITE_ADDRESS: 'yafeilee.me'
  | #Website Year for footer display
  | SITE_YEAR: '© 2017'
  |  
  | # optional
  | # google analytics, blank it if you don't need
  | GOOGLE: ''
  |  
  | # CDN ( optional )
  | CDN: ''
  |  
  | # Email Setting, see more: /config/environments/production.rb
  | MAIL_SERVER: ''
  | DOMAIN_NAME: ''
  | MAIL_USERNAME: ''
  | MAIL_PASSWORD: ''

`

然后我修改了一些，这是修改后的

![image](https://user-images.githubusercontent.com/22759331/27940563-f262e882-62fd-11e7-89fc-8d7700d5d59f.png)

重新启动服务  登陆 提示系统还未配置管理员用户：
![image](https://user-images.githubusercontent.com/22759331/27940594-1b3bcbca-62fe-11e7-8da2-cd3bc739cb64.png)

**Comment by windy** [comment]
配置应该没错, 下面的的提示不是没配置, 而可能是你写错地址了?

http://yourip:port/admin

**Comment by windy** [comment]
@babyhai 问题解决的怎么样?

**Comment by babyhai** [comment]
应该不是端口的问题， 我已经部署到服务器上了 ，在这之前在服务器上运行过 管理这一块是没有问题的 。后面评论那一块没有及时刷新 我解决这个问题  重新复制代码到服务器上呢 才出现这个问题的

**Comment by windy** [comment]
那就不清楚了, 自己研究一下吧, 这个不会是因为本身代码的问题的.

**Comment by babyhai** [comment]
ok
