### ISSUE TITLE
上传图片的问题

### ISSUE THREAD

**Issue by babyhai** [windy/wblog#54]
再后台管理页面，新建博客 输入了标签 标题 点击上传图片 打开一张图片 不显示图片 后台的日志

![riwf w03pho f5zkfw 07 y](https://user-images.githubusercontent.com/22759331/28405508-e3082f48-6d5f-11e7-859e-da8a63a8f4ac.png)

这是点击上传图片按钮之后 
![image](https://user-images.githubusercontent.com/22759331/28405658-07643922-6d60-11e7-82d6-3e1aa07c479e.png)

再第一个错误 提示模版有问题，我再views 下面创建了photos /create.html.slim 文件后 没有说模版错误 这个时候 点击上传图片按钮后  会把正页面的html代码 全部显示再输入框里面 后面发现 这个html代码是 app/assets/javascripts/admin/post.cffee 这个文件有误  因为我再这个文件测试 render 1111  也显示在F12里面了

**Comment by windy** [comment]
@babyhai 最近有个版本更新, 导致了问题, 我修复一下.

**Comment by windy** [comment]
@babyhai 已经修复
