### ISSUE TITLE
請教一下，因為我有上傳多個檔案和圖片的需求，將CKEditor+Paperclip套件加入了，但發布文章都不會成功！

### ISSUE THREAD

**Issue by afgnsu** [windy/wblog#78]
如題，都會跳出『Unpermitted parameters: :utf8, :authenticity_token, :post』錯誤！

![2021-06-11_153012](https://user-images.githubusercontent.com/7204469/121648985-a972a700-caca-11eb-9256-09ab85d77fb3.jpg)
![2021-06-11_153025](https://user-images.githubusercontent.com/7204469/121649004-ad9ec480-caca-11eb-8a6f-9a42e998198d.jpg)
![2021-06-11_153038](https://user-images.githubusercontent.com/7204469/121649043-b8f1f000-caca-11eb-95a8-a20197d88867.jpg)
![2021-06-11_153225](https://user-images.githubusercontent.com/7204469/121649053-bc857700-caca-11eb-9404-caeffa0ed1d9.jpg)

我有爬文看到這篇文章
[https://stackoverflow.com/questions/53597026/unpermitted-parameters-utf8-authenticity-token-rails-5-2-form-with](url)

嘗試：

def site_params
  params.require(:site).permit(:location_id, :place_id, :site_name, :review_url)
end
的參數site嵌套在params[:site]. 您應該首先從所有參數中取出這個哈希值，然後調用permit它。現在您正在清理所有參數（包括一些您顯然不感興趣的東西，例如utf8或authenticity_token）。

可是  app/controllers/admin/posts_controller.rb 裡面加入 

> private
>
>   def post_params
>     params.require(:post).permit(:title, :content)
>   end

也沒用，一樣是無法正常送出文章 >"<

麻煩您不吝指導，謝謝。

**Comment by windy** [comment]
我推荐你使用 https://trix-editor.org/  这个编辑器进行集成, ckeditor 有点太老了.

**Comment by afgnsu** [comment]
收到，謝謝您，我試試看 ^_^
